package io.jenkins.plugins.explain_error.autofix;

import com.cloudbees.plugins.credentials.CredentialsProvider;
import com.cloudbees.plugins.credentials.common.StandardUsernamePasswordCredentials;
import com.fasterxml.jackson.databind.ObjectMapper;
import hudson.model.AbstractProject;
import hudson.model.Item;
import hudson.model.Run;
import hudson.model.TaskListener;
import hudson.scm.SCM;
import hudson.util.Secret;
import io.jenkins.plugins.explain_error.autofix.scm.ScmApiClient;
import io.jenkins.plugins.explain_error.autofix.scm.ScmClientFactory;
import io.jenkins.plugins.explain_error.autofix.scm.PullRequest;
import io.jenkins.plugins.explain_error.autofix.scm.ScmRepo;
import io.jenkins.plugins.explain_error.autofix.scm.ScmType;
import io.jenkins.plugins.explain_error.provider.BaseAIProvider;
import jenkins.model.Jenkins;
import org.jenkinsci.plugins.plaincredentials.StringCredentials;

import java.io.IOException;
import java.lang.reflect.Method;
import java.net.URI;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.util.Collections;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.regex.Pattern;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Main coordinator for the AI auto-fix workflow.
 *
 * <p>Asks the configured AI provider for a fix suggestion, validates all file paths
 * and diffs, applies changes to a new branch via the SCM API, and opens a pull request.
 */
public class AutoFixOrchestrator {

    private static final Logger LOGGER = Logger.getLogger(AutoFixOrchestrator.class.getName());

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    /**
     * Dedicated thread pool for auto-fix operations. Uses daemon threads so the pool
     * does not prevent JVM shutdown; avoids polluting the ForkJoinPool.commonPool().
     */
    private static final ExecutorService EXECUTOR = Executors.newCachedThreadPool(r -> {
        Thread t = new Thread(r, "jenkins-autofix");
        t.setDaemon(true);
        return t;
    });

    /** Matches {@code {word}} placeholder tokens in PR body templates. */
    private static final Pattern TEMPLATE_PLACEHOLDER = Pattern.compile("\\{(\\w+)\\}");

    /** Default PR body template with {@code {variable}} placeholders. */
    private static final String DEFAULT_PR_TEMPLATE = """
            ## AI Auto-Fix for {jobName} #{buildNumber}

            This pull request was automatically generated by the [Explain Error Plugin](https://plugins.jenkins.io/explain-error) \
            to address a build failure.

            ### Root Cause

            {explanation}

            ### Changes

            {changesSummary}

            ### Build Details

            - **Job:** {jobName}
            - **Build:** #{buildNumber}
            - **Fix Type:** {fixType}
            - **Confidence:** {confidence}

            ---
            *Generated by AI Auto-Fix — please review all changes carefully before merging.*
            """;

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Attempts to automatically fix the build failure described by {@code errorLogs}.
     *
     * @param run                 the failing build run
     * @param errorLogs           the error logs to analyse
     * @param aiProvider          the configured AI provider
     * @param credentialsId       Jenkins credentials ID for SCM token
     * @param remoteUrl           explicit SCM remote URL; if null or blank, extracted from the job's SCM config
     * @param scmTypeOverride     optional override for SCM type detection ("github"/"gitlab"/"bitbucket")
     * @param githubEnterpriseUrl optional GitHub Enterprise API base URL (e.g. https://ghe.example.com)
     * @param gitlabUrl           optional self-hosted GitLab base URL
     * @param bitbucketUrl        optional self-hosted Bitbucket base URL
     * @param allowedPathGlobs    list of glob patterns that restrict which files may be changed
     * @param draftPr             whether to open a draft PR
     * @param timeoutSeconds      overall timeout in seconds
     * @param listener            task listener for build-log output
     * @return the result of the auto-fix attempt
     */
    public AutoFixResult attemptAutoFix(
            Run<?, ?> run,
            String errorLogs,
            BaseAIProvider aiProvider,
            String credentialsId,
            String remoteUrl,
            String scmTypeOverride,
            String githubEnterpriseUrl,
            String gitlabUrl,
            String bitbucketUrl,
            List<String> allowedPathGlobs,
            boolean draftPr,
            int timeoutSeconds,
            TaskListener listener,
            String prTemplate) {

        // We keep track of the branch name so we can clean up on timeout/failure.
        final String[] createdBranchRef = {null};

        CompletableFuture<AutoFixResult> future = CompletableFuture.supplyAsync(() -> {
            try {
                return doAttemptAutoFix(
                        run, errorLogs, aiProvider, credentialsId, remoteUrl,
                        scmTypeOverride, githubEnterpriseUrl, gitlabUrl, bitbucketUrl,
                        allowedPathGlobs, draftPr, listener, createdBranchRef, prTemplate);
            } catch (Exception e) {
                LOGGER.log(Level.WARNING, "Auto-fix failed with exception", e);
                listener.getLogger().println("[AutoFix] Error: " + e.getMessage());
                return AutoFixResult.failed("Auto-fix encountered an unexpected error: " + e.getMessage());
            }
        }, EXECUTOR);

        try {
            return future.get(timeoutSeconds, TimeUnit.SECONDS);
        } catch (TimeoutException e) {
            future.cancel(true);
            listener.getLogger().println("[AutoFix] Timed out after " + timeoutSeconds + " seconds.");
            // Best-effort branch cleanup
            if (createdBranchRef[0] != null) {
                try {
                    String resolvedUrl = (remoteUrl != null && !remoteUrl.isBlank())
                            ? remoteUrl : extractRemoteUrl(run);
                    String token = resolveScmToken(credentialsId, run);
                    if (token != null) {
                        ScmRepo repo = buildScmRepo(resolvedUrl, token,
                                scmTypeOverride, githubEnterpriseUrl, gitlabUrl, bitbucketUrl);
                        ScmApiClient client = ScmClientFactory.create(repo);
                        client.deleteBranch(createdBranchRef[0]);
                    }
                } catch (Exception ex) {
                    LOGGER.log(Level.WARNING, "Failed to clean up branch after timeout", ex);
                }
            }
            return AutoFixResult.timedOut();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return AutoFixResult.failed("Auto-fix interrupted.");
        } catch (ExecutionException e) {
            Throwable cause = e.getCause();
            LOGGER.log(Level.WARNING, "Auto-fix execution failed", cause);
            return AutoFixResult.failed("Auto-fix execution failed: " + (cause != null ? cause.getMessage() : e.getMessage()));
        }
    }

    // -------------------------------------------------------------------------
    // Core logic
    // -------------------------------------------------------------------------

    private AutoFixResult doAttemptAutoFix(
            Run<?, ?> run,
            String errorLogs,
            BaseAIProvider aiProvider,
            String credentialsId,
            String remoteUrl,
            String scmTypeOverride,
            String githubEnterpriseUrl,
            String gitlabUrl,
            String bitbucketUrl,
            List<String> allowedPathGlobs,
            boolean draftPr,
            TaskListener listener,
            String[] createdBranchRef,
            String prTemplate) throws Exception {

        listener.getLogger().println("[AutoFix] Requesting fix suggestion from AI provider...");

        // Early validation — fail before spending AI tokens
        if (credentialsId == null || credentialsId.isBlank()) {
            return AutoFixResult.failed("autoFixCredentialsId is required for auto-fix");
        }

        // Step 1 — Get AI fix suggestion
        FixAssistant fixAssistant = aiProvider.createFixAssistant(run.getParent(), null);
        String rawJson = fixAssistant.suggestFix(errorLogs);
        LOGGER.fine("Raw AI response: " + rawJson);
        FixSuggestion suggestion = parseFixSuggestion(rawJson);

        listener.getLogger().println("[AutoFix] AI suggestion: fixable=" + suggestion.fixable()
                + ", confidence=" + suggestion.confidence()
                + ", fixType=" + suggestion.fixType());

        // Step 2 — Check fixability
        if (!suggestion.fixable() || "low".equals(suggestion.confidence())) {
            listener.getLogger().println("[AutoFix] Skipping: AI confidence too low or not fixable.");
            return AutoFixResult.skippedLowConfidence();
        }

        if (suggestion.changes() == null || suggestion.changes().isEmpty()) {
            listener.getLogger().println("[AutoFix] Skipping: AI returned fixable=true but no file changes.");
            return AutoFixResult.skippedLowConfidence();
        }

        // Step 3 — Validate file paths
        if (suggestion.changes() != null) {
            for (FixSuggestion.FileChange change : suggestion.changes()) {
                String filePath = change.filePath();
                String pathError = validateFilePath(filePath, allowedPathGlobs);
                if (pathError != null) {
                    listener.getLogger().println("[AutoFix] Skipping: " + pathError);
                    return AutoFixResult.skippedPathNotAllowed(filePath);
                }
            }
        }

        // Step 4 — Validate all diffs
        if (suggestion.changes() != null) {
            for (FixSuggestion.FileChange change : suggestion.changes()) {
                if ("modify".equals(change.action())) {
                    String diffError = UnifiedDiffApplier.validate(change.unifiedDiff());
                    if (diffError != null) {
                        String msg = "Invalid diff for " + change.filePath() + ": " + diffError;
                        listener.getLogger().println("[AutoFix] Failed: " + msg);
                        return AutoFixResult.failed(msg);
                    }
                }
            }
        }

        // Step 5 — Detect SCM remote URL and credentials
        String resolvedRemoteUrl = (remoteUrl != null && !remoteUrl.isBlank())
                ? remoteUrl : extractRemoteUrl(run);
        listener.getLogger().println("[AutoFix] SCM remote: " + resolvedRemoteUrl);

        String token = resolveScmToken(credentialsId, run);
        if (token == null) {
            return AutoFixResult.failed("SCM credentials not found for ID: " + credentialsId);
        }

        // Step 6 — Parse SCM repo (with enterprise overrides)
        ScmRepo repo = buildScmRepo(resolvedRemoteUrl, token, scmTypeOverride,
                githubEnterpriseUrl, gitlabUrl, bitbucketUrl);
        listener.getLogger().println("[AutoFix] SCM type: " + repo.scmType()
                + ", owner: " + repo.owner() + ", repo: " + repo.repoName());

        ScmApiClient client = ScmClientFactory.create(repo);

        // Step 7 — Validate credentials / write access
        listener.getLogger().println("[AutoFix] Validating write access...");
        client.validateWriteAccess();

        // Determine default branch
        String defaultBranch = client.getDefaultBranch();
        listener.getLogger().println("[AutoFix] Default branch: " + defaultBranch);

        // Step 8 — Create fix branch
        String branchName = "fix/jenkins-ai-" + run.getNumber() + "-" + System.currentTimeMillis();
        listener.getLogger().println("[AutoFix] Creating branch: " + branchName);
        client.createBranch(branchName, defaultBranch);
        createdBranchRef[0] = branchName;

        // Step 9 — Apply diffs, collect new file contents
        Map<String, String> fileContents = new LinkedHashMap<>();
        if (suggestion.changes() != null) {
            for (FixSuggestion.FileChange change : suggestion.changes()) {
                String filePath = change.filePath();
                listener.getLogger().println("[AutoFix] Preparing change for: " + filePath + " (" + change.action() + ")");

                String currentContent = client.getFileContent(filePath, defaultBranch);

                String newContent;
                if ("create".equals(change.action())) {
                    newContent = extractNewContent(change.unifiedDiff());
                } else {
                    // modify
                    if (currentContent == null) {
                        String msg = "Cannot modify non-existent file: " + filePath;
                        listener.getLogger().println("[AutoFix] Failed: " + msg);
                        rollbackBranch(client, branchName, listener);
                        return AutoFixResult.failed(msg);
                    }
                    try {
                        newContent = UnifiedDiffApplier.apply(currentContent, change.unifiedDiff());
                    } catch (IllegalArgumentException e) {
                        String msg = "Failed to apply diff to " + filePath + ": " + e.getMessage();
                        listener.getLogger().println("[AutoFix] Failed: " + msg);
                        rollbackBranch(client, branchName, listener);
                        return AutoFixResult.failed(msg);
                    }
                }
                fileContents.put(filePath, newContent);
            }
        }

        // Commit all changes atomically
        String commitMessage = "fix: AI auto-fix for build #" + run.getNumber();
        try {
            client.commitFiles(branchName, commitMessage, fileContents);
        } catch (IOException e) {
            String msg = "Failed to commit files: " + e.getMessage();
            listener.getLogger().println("[AutoFix] Failed: " + msg);
            rollbackBranch(client, branchName, listener);
            return AutoFixResult.failed(msg);
        }

        // Step 10 — Create PR
        String prTitle = "fix: AI auto-fix for " + run.getParent().getFullName() + " #" + run.getNumber();
        String effectiveTemplate = (prTemplate != null && !prTemplate.isBlank()) ? prTemplate : DEFAULT_PR_TEMPLATE;
        String prBody = buildPrBody(run, suggestion, effectiveTemplate);

        PullRequest pr;
        try {
            pr = client.createPullRequest(prTitle, prBody, branchName, defaultBranch, draftPr);
        } catch (IOException e) {
            String msg = "Failed to create pull request: " + e.getMessage();
            listener.getLogger().println("[AutoFix] Failed: " + msg);
            rollbackBranch(client, branchName, listener);
            return AutoFixResult.failed(msg);
        }

        listener.getLogger().println("[AutoFix] Pull request created: " + pr.url());

        // Step 11 — Store action and return
        AutoFixAction action = new AutoFixAction(
                AutoFixStatus.CREATED,
                pr.url(),
                branchName,
                "PR created: " + pr.url(),
                prTitle,
                System.currentTimeMillis(),
                repo.scmType().name());
        run.addOrReplaceAction(action);
        try {
            run.save();
        } catch (IOException e) {
            LOGGER.log(Level.WARNING, "Failed to persist AutoFixAction to build", e);
        }

        return AutoFixResult.created(pr.url(), branchName);
    }

    // -------------------------------------------------------------------------
    // Helper methods
    // -------------------------------------------------------------------------

    String resolveScmToken(String credentialsId, Run<?, ?> run) {
        StringCredentials stringCredentials = CredentialsProvider.findCredentialById(
                credentialsId, StringCredentials.class, run, Collections.emptyList());
        if (stringCredentials != null) {
            return Secret.toString(stringCredentials.getSecret());
        }

        StandardUsernamePasswordCredentials usernamePasswordCredentials = CredentialsProvider.findCredentialById(
                credentialsId, StandardUsernamePasswordCredentials.class, run, Collections.emptyList());
        if (usernamePasswordCredentials != null) {
            return Secret.toString(usernamePasswordCredentials.getPassword());
        }

        return null;
    }

    /**
     * Parses a raw string from the AI (which may contain preamble) into a {@link FixSuggestion}.
     * Extracts the JSON block by finding the first '{' and last '}'.
     */
    FixSuggestion parseFixSuggestion(String rawJson) throws IOException {
        if (rawJson == null || rawJson.isBlank()) {
            throw new IOException("AI returned empty response");
        }
        int start = rawJson.indexOf('{');
        int end = rawJson.lastIndexOf('}');
        if (start < 0 || end < 0 || start >= end) {
            throw new IOException("No JSON object found in AI response: " + rawJson);
        }
        String jsonBlock = rawJson.substring(start, end + 1);
        return OBJECT_MAPPER.readValue(jsonBlock, FixSuggestion.class);
    }

    /**
     * Validates a file path against security constraints and the allowed-path globs.
     *
     * @return null if path is valid, or a description of why it was rejected
     */
    private String validateFilePath(String filePath, List<String> allowedPathGlobs) {
        if (filePath == null || filePath.isBlank()) {
            return "File path is null or blank";
        }
        if (filePath.startsWith("/")) {
            return "Absolute paths are not allowed: " + filePath;
        }
        // Normalize to catch trailing ".." segments (e.g. "src/main/..") that would
        // bypass a simple string-contains check. Also catches Windows-style "..\".
        Path normalized = Path.of(filePath).normalize();
        if (normalized.startsWith("..")) {
            return "Path traversal is not allowed: " + filePath;
        }
        if (allowedPathGlobs != null && !allowedPathGlobs.isEmpty()) {
            boolean matched = false;
            Path p = Path.of(filePath);
            for (String glob : allowedPathGlobs) {
                try {
                    PathMatcher matcher = FileSystems.getDefault().getPathMatcher("glob:" + glob);
                    Path fileName = p.getFileName();
                    if (matcher.matches(p) || (fileName != null && matcher.matches(fileName))) {
                        matched = true;
                        break;
                    }
                } catch (Exception e) {
                    LOGGER.warning("Invalid glob pattern '" + glob + "': " + e.getMessage());
                }
            }
            if (!matched) {
                return "File path '" + filePath + "' is not allowed by configured path patterns";
            }
        }
        return null;
    }

    /**
     * Extracts the remote URL from the run's SCM configuration via reflection (to avoid
     * a hard compile-time dependency on the git plugin).
     */
    String extractRemoteUrl(Run<?, ?> run) {
        SCM scm = extractConfiguredScm(run.getParent());
        if (scm == null) {
            throw new IllegalStateException("No SCM configured on this job");
        }
        return extractGitRemoteUrl(scm);
    }

    private SCM extractConfiguredScm(Item job) {
        if (job instanceof AbstractProject<?, ?> project) {
            return project.getScm();
        }

        SCM fromScmsMethod = extractFirstScmFromMethod(job, "getSCMs");
        if (fromScmsMethod != null) {
            return fromScmsMethod;
        }

        try {
            Method getDefinition = job.getClass().getMethod("getDefinition");
            Object definition = getDefinition.invoke(job);
            if (definition != null) {
                SCM fromDefinition = extractScmFromDefinition(definition);
                if (fromDefinition != null) {
                    return fromDefinition;
                }
            }
        } catch (NoSuchMethodException e) {
            LOGGER.fine("Job type does not expose getDefinition(): " + job.getClass().getName());
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("Failed to inspect SCM definition for job type "
                    + job.getClass().getName() + ": " + e.getMessage(), e);
        }

        throw new IllegalStateException("Job type " + job.getClass().getName()
                + " does not support SCM URL extraction");
    }

    private SCM extractScmFromDefinition(Object definition) throws ReflectiveOperationException {
        SCM scm = extractScmFromMethod(definition, "getScm");
        if (scm != null) {
            return scm;
        }
        return extractFirstScmFromMethod(definition, "getSCMs");
    }

    private SCM extractScmFromMethod(Object target, String methodName) throws ReflectiveOperationException {
        try {
            Method method = target.getClass().getMethod(methodName);
            Object result = method.invoke(target);
            if (result instanceof SCM scm) {
                return scm;
            }
            return null;
        } catch (NoSuchMethodException e) {
            return null;
        }
    }

    private SCM extractFirstScmFromMethod(Object target, String methodName) {
        try {
            Method method = target.getClass().getMethod(methodName);
            Object result = method.invoke(target);
            if (result instanceof Collection<?> collection) {
                Iterator<?> iterator = collection.iterator();
                while (iterator.hasNext()) {
                    Object candidate = iterator.next();
                    if (candidate instanceof SCM scm) {
                        return scm;
                    }
                }
            }
            return null;
        } catch (NoSuchMethodException e) {
            return null;
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("Failed to inspect SCMs via " + methodName + ": " + e.getMessage(), e);
        }
    }

    private String extractGitRemoteUrl(SCM scm) {
        String scmClassName = scm.getClass().getName();

        try {
            Method getRepositories = scm.getClass().getMethod("getRepositories");
            @SuppressWarnings("unchecked")
            List<?> repos = (List<?>) getRepositories.invoke(scm);
            if (!repos.isEmpty()) {
                Object repo = repos.get(0);
                Method getUrls = repo.getClass().getMethod("getURIs");
                @SuppressWarnings("unchecked")
                List<?> uris = (List<?>) getUrls.invoke(repo);
                if (!uris.isEmpty()) {
                    return uris.get(0).toString();
                }
            }
        } catch (NoSuchMethodException e) {
            throw new IllegalStateException(
                    "Unsupported SCM type: " + scmClassName + ". Only GitSCM is currently supported.");
        } catch (Exception e) {
            throw new IllegalStateException("Failed to extract remote URL from GitSCM: " + e.getMessage(), e);
        }
        throw new IllegalStateException("No Git remote URLs configured for SCM type: " + scmClassName);
    }

    /**
     * Builds a {@link ScmRepo} from the remote URL and applies any enterprise URL overrides.
     *
     * <p>When {@code scmTypeOverride} is specified, it bypasses URL-based host detection —
     * required for self-hosted instances (e.g. {@code git.company.com}) whose hostname
     * does not match {@code github.com}, {@code gitlab.com}, or {@code bitbucket.org}.
     */
    private ScmRepo buildScmRepo(String remoteUrl, String token, String scmTypeOverride,
                                  String githubEnterpriseUrl, String gitlabUrl, String bitbucketUrl) {
        // If scmTypeOverride is provided, use it directly so self-hosted instances work.
        if (scmTypeOverride != null && !scmTypeOverride.isBlank()) {
            ScmType forcedType;
            switch (scmTypeOverride.trim().toLowerCase()) {
                case "github":          forcedType = ScmType.GITHUB;          break;
                case "gitlab":          forcedType = ScmType.GITLAB;          break;
                case "bitbucket":       forcedType = ScmType.BITBUCKET;       break;
                case "bitbucketserver": forcedType = ScmType.BITBUCKET_SERVER; break;
                default:
                    LOGGER.warning("Unrecognised scmTypeOverride '" + scmTypeOverride
                            + "' — falling back to URL-based detection");
                    forcedType = null;
            }
            if (forcedType != null) {
                String baseUrl;
                switch (forcedType) {
                    case GITHUB:
                        baseUrl = (githubEnterpriseUrl != null && !githubEnterpriseUrl.isBlank())
                                ? githubEnterpriseUrl.stripTrailing() + "/api/v3"
                                : "https://api.github.com";
                        break;
                    case GITLAB:
                        baseUrl = (gitlabUrl != null && !gitlabUrl.isBlank())
                                ? gitlabUrl.stripTrailing() + "/api/v4"
                                : "https://gitlab.com/api/v4";
                        break;
                    case BITBUCKET:
                        baseUrl = resolveCloudBitbucketBaseUrl(bitbucketUrl);
                        break;
                    case BITBUCKET_SERVER:
                        if (bitbucketUrl == null || bitbucketUrl.isBlank()) {
                            throw new IllegalArgumentException(
                                    "autoFixBitbucketUrl must be set when scmTypeOverride is 'bitbucketserver'");
                        }
                        baseUrl = bitbucketUrl.stripTrailing() + "/rest/api/1.0";
                        break;
                    default:
                        baseUrl = null; // unreachable
                }
                return ScmRepo.parseWithOverride(remoteUrl, token, forcedType, baseUrl);
            }
        }

        ScmRepo repo = ScmRepo.parse(remoteUrl, token);

        // Apply enterprise base-URL overrides when the host was auto-detected
        if (repo.scmType() == ScmType.GITHUB && githubEnterpriseUrl != null && !githubEnterpriseUrl.isBlank()) {
            repo = repo.withBaseUrl(githubEnterpriseUrl.stripTrailing() + "/api/v3");
        } else if (repo.scmType() == ScmType.GITLAB && gitlabUrl != null && !gitlabUrl.isBlank()) {
            repo = repo.withBaseUrl(gitlabUrl.stripTrailing() + "/api/v4");
        } else if (repo.scmType() == ScmType.BITBUCKET && bitbucketUrl != null && !bitbucketUrl.isBlank()) {
            repo = repo.withBaseUrl(resolveCloudBitbucketBaseUrl(bitbucketUrl));
        } else if (repo.scmType() == ScmType.BITBUCKET_SERVER && bitbucketUrl != null && !bitbucketUrl.isBlank()) {
            repo = repo.withBaseUrl(bitbucketUrl.stripTrailing() + "/rest/api/1.0");
        }

        return repo;
    }

    String resolveCloudBitbucketBaseUrl(String bitbucketUrl) {
        if (bitbucketUrl == null || bitbucketUrl.isBlank()) {
            return "https://api.bitbucket.org/2.0";
        }

        String normalized = bitbucketUrl.stripTrailing();
        URI uri = URI.create(normalized);
        String host = uri.getHost();
        if (host == null) {
            throw new IllegalArgumentException("Bitbucket URL is not a valid absolute URL: " + bitbucketUrl);
        }

        if (normalized.endsWith("/2.0")) {
            return normalized;
        }
        return "https://api.bitbucket.org/2.0";
    }

    /**
     * Extracts the new file content from a unified diff (for "create" actions).
     * Collects all lines starting with '+' (excluding the '+++' header).
     */
    String extractNewContent(String unifiedDiff) {
        if (unifiedDiff == null || unifiedDiff.isBlank()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        String[] lines = unifiedDiff.split("\r?\n", -1);
        boolean inHunk = false;
        for (String line : lines) {
            if (line.startsWith("@@ ")) {
                inHunk = true;
                continue;
            }
            if (line.startsWith("+++ ") || line.startsWith("--- ")) {
                continue;
            }
            if (inHunk && line.startsWith("+")) {
                if (sb.length() > 0) {
                    sb.append("\n");
                }
                sb.append(line.substring(1));
            }
        }
        return sb.toString();
    }

    /**
     * Builds a Markdown PR body by substituting {@code {variable}} placeholders in the template.
     */
    String buildPrBody(Run<?, ?> run, FixSuggestion suggestion, String template) {
        String jobName = run.getParent().getFullName();
        String buildNumber = String.valueOf(run.getNumber());
        String explanation = suggestion.explanation() != null ? suggestion.explanation() : "No explanation provided.";
        String confidence = suggestion.confidence() != null ? suggestion.confidence() : "unknown";
        String fixType = suggestion.fixType() != null ? suggestion.fixType() : "unknown";

        StringBuilder changesSummary = new StringBuilder();
        if (suggestion.changes() != null) {
            for (FixSuggestion.FileChange change : suggestion.changes()) {
                changesSummary.append("- **")
                        .append(change.filePath())
                        .append("** (")
                        .append(change.action())
                        .append("): ")
                        .append(change.description() != null ? change.description() : "")
                        .append("\n");
            }
        }
        if (changesSummary.isEmpty()) {
            changesSummary.append("No file changes.\n");
        }

        // Build values map and substitute all placeholders in a single pass so that
        // AI-provided content (explanation, descriptions) cannot match and corrupt
        // subsequent placeholder tokens (e.g. if explanation itself contains "{fixType}").
        Map<String, String> values = Map.of(
                "jobName", jobName,
                "buildNumber", buildNumber,
                "explanation", explanation,
                "changesSummary", changesSummary.toString().stripTrailing(),
                "fixType", fixType,
                "confidence", confidence
        );
        return TEMPLATE_PLACEHOLDER.matcher(template).replaceAll(m -> {
            String val = values.get(m.group(1));
            return val != null ? val : m.group(0);
        });
    }

    /**
     * Attempts to delete the given branch for rollback purposes. Logs but does not throw on failure.
     */
    private void rollbackBranch(ScmApiClient client, String branchName, TaskListener listener) {
        try {
            listener.getLogger().println("[AutoFix] Rolling back branch: " + branchName);
            client.deleteBranch(branchName);
        } catch (IOException e) {
            LOGGER.log(Level.WARNING, "Failed to delete branch during rollback: " + branchName, e);
        }
    }
}
